"""init_table

Revision ID: a3cb4e295e50
Revises: 
Create Date: 2023-04-03 23:50:42.977438

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a3cb4e295e50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('birth_place', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
